export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const AUTHORIZE_FACEBOOK = 'login/AUTHORIZE_FACEBOOK';
export const AUTHORIZED_FACEBOOK = 'login/AUTHORIZED_FACEBOOK';